server:
  port: 8083

spring:
  application:
    name: order-service
  boot:
    admin:
      client:
        url: http://localhost:8085
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      myService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # 10 secondes
        permittedNumberOfCallsInHalfOpenState: 3
